# Generated by Django 2.1.7 on 2019-03-01 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='driver',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='trucks.Driver'),
        ),
        migrations.AddField(
            model_name='driver',
            name='path',
            field=models.CharField(default='', max_length=200),
        ),
    ]
