# Generated by Django 2.1.3 on 2019-03-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JioKisan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
