# Generated by Django 2.1.3 on 2019-02-22 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JioKisan', '0007_user_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consignment',
            fields=[
                ('ucid', models.IntegerField(primary_key=True, serialize=False)),
                ('expected_delivery', models.DateField()),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FarmEntity',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('PTS', models.CharField(max_length=40)),
                ('measured_in', models.CharField(max_length=40)),
                ('MSP', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('upid', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('FE_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JioKisan.FarmEntity')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('urid', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('current_bid', models.IntegerField()),
                ('before_date', models.DateField()),
                ('FE_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JioKisan.FarmEntity')),
            ],
        ),
        migrations.RemoveField(
            model_name='sellable',
            name='categary',
        ),
        migrations.RemoveField(
            model_name='sellable',
            name='seller',
        ),
        migrations.AddField(
            model_name='user_reg',
            name='bank_account_number',
            field=models.CharField(default=12, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_reg',
            name='license_number',
            field=models.CharField(default=12, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_reg',
            name='organisation_name',
            field=models.CharField(default=12, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_reg',
            name='vehicle_capacity',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_reg',
            name='vehicle_model',
            field=models.CharField(default=12, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_reg',
            name='vehicle_number',
            field=models.CharField(default=12, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='phone_number',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.DeleteModel(
            name='Categary',
        ),
        migrations.DeleteModel(
            name='PhoneUser',
        ),
        migrations.DeleteModel(
            name='Sellable',
        ),
        migrations.AddField(
            model_name='request',
            name='mandi_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JioKisan.User_reg'),
        ),
        migrations.AddField(
            model_name='produce',
            name='farmer_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JioKisan.User_reg'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JioKisan.Produce'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='req',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JioKisan.Request'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JioKisan.User_reg'),
        ),
    ]
