# Generated by Django 2.1.3 on 2019-02-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JioKisan', '0008_auto_20190222_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmentity',
            name='PTS',
        ),
        migrations.RemoveField(
            model_name='farmentity',
            name='id',
        ),
        migrations.RemoveField(
            model_name='farmentity',
            name='price',
        ),
        migrations.AddField(
            model_name='farmentity',
            name='ufid',
            field=models.IntegerField(default=123, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farmentity',
            name='measured_in',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='farmentity',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='vehicle_model',
            field=models.IntegerField(),
        ),
    ]
