# Generated by Django 2.1.3 on 2019-02-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JioKisan', '0009_auto_20190222_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmentity',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
