# Generated by Django 2.1.3 on 2019-02-22 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JioKisan', '0010_auto_20190222_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='prod',
            field=models.ForeignKey(db_column='upid', on_delete=django.db.models.deletion.CASCADE, to='JioKisan.Produce'),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='req',
            field=models.ForeignKey(db_column='urid', on_delete=django.db.models.deletion.CASCADE, to='JioKisan.Request'),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='truck',
            field=models.ForeignKey(db_column='PAN', on_delete=django.db.models.deletion.CASCADE, to='JioKisan.User_reg'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='FE_info',
            field=models.ForeignKey(db_column='ufid', on_delete=django.db.models.deletion.CASCADE, to='JioKisan.FarmEntity'),
        ),
        migrations.AlterField(
            model_name='request',
            name='FE_info',
            field=models.ForeignKey(db_column='ufid', on_delete=django.db.models.deletion.CASCADE, to='JioKisan.FarmEntity'),
        ),
        migrations.AlterField(
            model_name='request',
            name='mandi_info',
            field=models.ForeignKey(db_column='PAN', on_delete=django.db.models.deletion.CASCADE, to='JioKisan.User_reg'),
        ),
    ]
