# Generated by Django 2.1.3 on 2019-02-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JioKisan', '0011_auto_20190222_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_reg',
            old_name='license_number',
            new_name='GST_number',
        ),
        migrations.AddField(
            model_name='user_reg',
            name='isVerified',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_reg',
            name='licence_number',
            field=models.CharField(default=455, max_length=20),
            preserve_default=False,
        ),
    ]
