# Generated by Django 2.1.3 on 2019-02-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JioKisan', '0012_auto_20190224_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='GST_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='bank_account_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='licence_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='organisation_name',
            field=models.CharField(blank=True, default=None, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='vehicle_capacity',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='vehicle_model',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='vehicle_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
