# Generated by Django 2.1 on 2019-02-26 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JioKisan', '0013_auto_20190224_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='farmer_info',
            field=models.ForeignKey(db_column='PAN', on_delete=django.db.models.deletion.CASCADE, to='JioKisan.User_reg'),
        ),
    ]
