# Generated by Django 2.1.3 on 2019-03-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JioKisan', '0015_auto_20190301_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_reg',
            old_name='current_position_latitude',
            new_name='position_latitude',
        ),
        migrations.RenameField(
            model_name='user_reg',
            old_name='current_position_longitude',
            new_name='position_longitude',
        ),
        migrations.AddField(
            model_name='consignment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('TRANSIT', 'Transit'), ('COMPLETED', 'Completed')], default=None, max_length=25),
            preserve_default=False,
        ),
    ]
