# Generated by Django 2.1.3 on 2019-03-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JioKisan', '0016_auto_20190301_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('TRANSIT', 'Transit'), ('COMPLETED', 'Completed')], default='PENDING', max_length=25),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='ucid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='farmentity',
            name='ufid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produce',
            name='upid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='urid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
