# Generated by Django 2.1.3 on 2019-03-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JioKisan', '0017_auto_20190301_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmentity',
            name='display_image',
            field=models.ImageField(blank=True, upload_to='fe_sample_images'),
        ),
    ]
