# Generated by Django 2.1.3 on 2019-03-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JioKisan', '0018_farmentity_display_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='isAsigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='isAsigned',
            field=models.BooleanField(default=False),
        ),
    ]
