# Generated by Django 2.1.3 on 2019-03-02 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JioKisan', '0019_auto_20190302_0610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produce',
            old_name='isAsigned',
            new_name='isAssigned',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='isAsigned',
            new_name='isAssigned',
        ),
    ]
