# Generated by Django 2.1.3 on 2019-03-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JioKisan', '0020_auto_20190302_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmentity',
            name='isFarmTool',
            field=models.BooleanField(default=False),
        ),
    ]
